# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  registryName: demodevinda.azurecr.io
  imageRepository: mutistage-cache

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build prod dependencies
      env:
        DOCKER_BUILDKIT: 1
      inputs:
        command: 'build'
        repository: '$(imageRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: demodevinda
        arguments: '--target prod-deps'
        arguments: '--cache-from=$(registryName)/$(imageRepository):latest-prod-deps'
        tags: |
          latest-prod-deps
    - task: Docker@2
      displayName: Build running image
      env:
        DOCKER_BUILDKIT: 1
      inputs:
        command: buildAndPush
        repository: '$(imageRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: demodevinda
        arguments: '--cache-from=$(registryName)/$(imageRepository):latest-prod-deps --cache-from=$(registryName)/$(imageRepository):latest'
        tags: |
          latest
    
