# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  registryName: demodevinda.azurecr.io
  containerRegistry: demodevinda
  imageRepository: mutistage-cache

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: "Registry Login"
      inputs:
        containerRegistry: '$(containerRegistry)'
        command: 'login'
    - task: Cache@2
      displayName: Cache task
      inputs:
        key: 'docker | "$(Agent.OS)" | "$(Build.SourceVersion)"'
        path: /tmp/.buildx-cache
        restoreKeys: 'docker | "$(Agent.OS)"' 
    - bash: docker buildx create --driver docker-container --use
      displayName: Create Buildkit container
    - bash: 
        docker buildx build --cache-to type=local,dest=/tmp/.buildx-cache/prod-deps --cache-from type=local,src=/tmp/.buildx-cache/prod-deps --target prod-deps --tag $(registryName)/$(imageRepository):latest-prod-deps .
      displayName: 'Build production dependencies'
    - bash: docker buildx build --cache-to type=local,mode=max,dest=/tmp/.buildx-cache/complete --cache-from type=local,src=/tmp/.buildx-cache/complete --push --tag $(registryName)/$(imageRepository):latest .
      displayName: 'Build completed image'
